project:
  type: website

website:
  title: "reluctant criminologists"
  site-url: https://www.reluctantcriminologists.com
  google-analytics: "G-F0XQR72SS3"
  description: "Jon Brauer and Jake Day's blog and course materials."
  navbar:
    logo: "images/RC_banner.jpg"
    left:
      - text: "About"
        href: about.qmd
      - text: "blog"
        href: blog-posts.qmd
      - text: "courses"
        href: course-materials.qmd
      - text: "supplementary"
        href: supp/index.qmd
      - text: "links"
        href: blog-posts/[2]/favorite_links.qmd
    right:
      - icon: envelope-fill
        href: mailto:reluctantcrim@gmail.com
      - icon: github
        href: https://github.com/jakeday4/reluctantcrim_website
      - icon: twitter
        href: https://twitter.com/reluctantcrim
  page-footer: 
    background: dark
    left:
        - icon: house-fill
          href: https://reluctantcriminologists.com/
      # - text: "Copyright CC-BY 4.0 unless otherwise noted."
      #   href: https://creativecommons.org/licenses/by/4.0/
    right: 
      - icon: envelope-fill
        href: mailto:reluctantcrim@gmail.com
      - icon: github
        href: https://github.com/jakeday4/reluctantcrim_website
      - icon: twitter 
        href: https://twitter.com/reluctantcrim 
format:
  html:
    theme: sandstone
    css: styles.css
    include-after-body: ./footer.html


