project:
  type: website

website:
  title: "reluctant criminologists"
  site-url: https://www.reluctantcriminologists.com
  description: "Jon Brauer and Jake Day's blog and course materials."
  navbar:
    logo: "images/RC_banner.jpg"
    left:
      - text: "About"
        href: about.qmd
      - text: "blog posts"
        href: blog-posts.qmd
      - text: "course materials"
        href: course-materials.qmd
      - text: "links we love"
        href: blog-posts/[2]/favorite_links.qmd
    right:
      - icon: envelope
        href: mailto:reluctantcrim@gmail.com
      # - icon: github
      #   href: https://github.com/
      # - icon: twitter
      #   href: https://twitter.com
format:
  html:
    theme: sandstone
    css: styles.css



